### ISSUE TITLE
We need more healthy fruit

### ISSUE THREAD

**Issue by hansvancalster** [hansvancalster/gitopleiding#2]
@damianooldoni  Can we add some more fruit to the csv file?

**Comment by damianooldoni** [comment]
Yes, I will to do it asap. I will do it in a new branch.

**Comment by hansvancalster** [comment]
Great Thanks!

**Comment by damianooldoni** [comment]
Hi @hansvancalster, I think I tackled successfully your issue here: 1a62ba4f2a01728154b579a34c94ac5307573575

**Comment by hansvancalster** [comment]
Please do a PR

**Comment by damianooldoni** [comment]
Ok. I will first implement your comments on https://github.com/hansvancalster/gitopleiding/commit/1a62ba4f2a01728154b579a34c94ac5307573575

**Comment by hansvancalster** [comment]
:+1:
